# Site settings
title: Hospoda.Tech
subtitle: Podcast o IT, zarządzaniu i biznesie
email: kontakt@hospoda.tech
author:
  name: Wojciech Nowicki
  url: https://wojciechnowicki.com
  twitter: wonowicki
  github: wnowicki
description: >- # this means to ignore newlines until "baseurl:"
  Spotkania przy mikrofonie niczym przy piwie w czeskiej hospodzie: konkret, praktyka, zero zadęcia. Rozmowy o IT, zarządzaniu, strategii, produktach, startupach i wszystkim, co dzieje się między deployem a KPI. Dla liderów technicznych, product ownerów i wszystkich, którzy łączą technologię z biznesem.
keywords: IT, PHP, agile, oop, Raspberry Pi, photography, scrum, software development, software architecture, e-commerce, git, opensource
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hospoda.tech" # the base hostname & protocol for your site
default_background: "/assets/img/background.jpg"

timezone: "Europe/Warsaw" # e.g. "America/New_York"
# Build settings
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll_version_plugin
  - jekyll-toc
  - jekyll-og-image
  - jekyll-twitter-plugin
markdown: kramdown

permalink: :title
paginate: 10
paginate_path: episodes/:num
# page_excerpts: true

collections:
  people:
    permalink: /osoby/:name
    output: true

jekyll_admin:
    homepage: "index"
    hidden_links:
      - datafiles

# Personalisation
social:
    spotify:
        footer: true
        url: https://open.spotify.com/show/63rDHoShb9uyRFW9oBLTBQ?si=S4mDfmdMTP6zPrUrMJJcwA
        icon: fa-brands fa-spotify
    apple-podcasts:
        footer: true
        url: https://podcasts.apple.com/pl/podcast/hospoda-tech/id1829767915
        icon: fa-brands fa-apple
    youtube:
        footer: true
        url: https://youtube.com/@HospodaTech
        icon: fa-brands fa-youtube
    twitter:
        footer: true
        url: https://x.com/HospodaTech
        icon: fa-brands fa-twitter
    bluesky:
        footer: true
        url: https://bsky.app/profile/hospoda.tech
        icon: fa-brands fa-bluesky
    facebook:
        footer: true
        url: https://www.facebook.com/HospodaTech
        icon: fa-brands fa-facebook
    linkedin:
        footer: true
        url: https://www.linkedin.com/company/hospoda-tech
        icon: fa-brands fa-linkedin
    github:
        footer: false
        url: https://github.com/
        icon: fa-brands fa-github
    discord:
        footer: false
        url: https://discord.com/users/985806052354306059
        icon: fa-brands fa-discord
    instagram:
        footer: true
        url: https://www.instagram.com/hospoda.tech
        icon: fa-brands fa-instagram

languages:
    pl:
        flag: pl
        name: Polski

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: 'tags/:name/'
    category: 'categories/:name/'

toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6

jekyll_compose:
  default_front_matter:
    drafts:
      subtitle:
      post_id:
      author:
      categories:
      heading_image:
      language:
      tags:

# Plugin: jekyll-og-image
og_image:
  collections: ["posts", "people"]
  output_dir: /assets/img/og
  domain: "hospoda.tech"
  image: /assets/img/hospoda-logo-square.jpg
  header:
    font_family: "Roboto, Bold"
    color: "#FFFFFF"
  content:
    font_family: "Roboto, Bold"
    color: "#FFFFFF"
  canvas:
    background_image: "/assets/img/background.jpg"
  border_bottom:
    width: 20
    fill:
      - "#ff7800"

# Plugin: jekyll-seo-tag
logo: /assets/img/hospoda-logo-square.jpg
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: /assets/img/og-main.jpg

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
